            - name: action-zip
- uses: montudor/action-zip@v1
  with:
    args: zip -qq -r dir.zip dir
    - uses: montudor/action-zip@v1
  with:
    args: unzip -qq dir.zip -d dir
    - name: Install zip
  uses: montudor/action-zip@v1

- name: Zip output
  run: zip -qq -r function.zip dist node_modules package.json
  working-directory: path/to/work-dir
